### PR TITLE
Refactor monkey patching

### LINKED ISSUE #46: Unable to access context.test in before_scenario
We've set up `before_scenario` to swap out Django's test client with Django Rest Framework's `APIClient`:

```
from rest_framework.test import APIClient

def before_scenario(context, scenario):
    context.test.client = APIClient()
```

This worked in 0.5.0. In 1.0.0, it seems that I can't access `context.test` at this point:

```
Exception AttributeError: 'PatchedContext' object has no attribute 'test'
Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    main()
  File "manage.py", line 26, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/behave_django/management/commands/behave.py", line 128, in handle
    exit_status = behave_main(args=behave_args)
  File "/usr/local/lib/python3.6/site-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 693, in run_with_paths
    return self.run_model()
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 471, in run_model
    self.run_hook('before_all', context)
  File "/usr/local/lib/python3.6/site-packages/behave_django/environment.py", line 91, in run_hook
    behave_run_hook(self, name, context, *args)
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 405, in run_hook
    self.hooks[name](context, *args)
  File "features/environment.py", line 14, in before_all
    context.test.client = APIClient()
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 214, in __getattr__
    raise AttributeError(msg)
AttributeError: 'PatchedContext' object has no attribute 'test'
```

As far as I can tell, I should be able to access `context.test` here.

### PR DESCRIPTION
**Pull request by mixxorz**
This fixes the regression in 1.0.0 where the `test` instance is no longer
available during the `before_scenario` hook.

This PR adds a new `django_setup` hook where you can run Django aware code
before each scenario. The `test` instance is made available in the context and
the method is run inside a transaction.

- [x] Add docs
- [x] Update CHANGELOG

Fixes #46

### CODE REVIEW

**Comment by mixxorz** [comment]
Please review. @bittner  :grin:

**Comment by mixxorz** [comment]
I'm okay with `django_ready`. I'll update it. 😁

File: docs/usage.rst [hunk 1]
```diff
@@ -90,19 +90,36 @@ regular TestCases.  So you can do something like:
...
+basis, you can initialize them in ``environment.py`` like this:
 
 .. code-block:: python
 
     from myapp.main.tests.factories import UserFactory, RandomContentFactory
 
 
-    def before_scenario(context, scenario):
+    def django_ready(context, scenario):
+        # This method is run inside the transaction
```
Comment (bittner) [inline docs/usage.rst]: Does this comment demonstrate that the function name doesn't explain it all? Or why do we have to explain that "now we're finally inside a Django test case"?

I'm not criticizing just trying to think aloud.

File: features/running-tests.feature [hunk 2]
```diff
@@ -7,3 +7,7 @@ Feature: Running tests
         Given this step exists
         When I run "python manage.py behave"
         Then I should see the behave tests run
+
+    Scenario: Test django_ready
+        When I run "python manage.py behave"
+        Then context.django should be declared
```
Comment (bittner) [inline features/running-tests.feature]: I think the `Then` shouldn't refer to the test implementation. Maybe `Then a running Django instance is available in django_ready`, or so? (Oh, horribly long sentence!)

File: features/steps/running_tests.py [hunk 3]
```diff
@@ -14,3 +14,8 @@ def run_command(context):
 @then(u'I should see the behave tests run')
 def is_running(context):
     pass
+
+
+@then(u'context.django should be declared')
+def django_context(context):
+    assert context.django
```
Comment (bittner) [inline features/steps/running_tests.py]: Is this a correct test? What if the code piece calling the hook is removed from the code? Then this won't be called and will not fail.

Comment (bittner) [reply features/steps/running_tests.py]: Stupid me! This step is called by _behave_ in any case! :blush: So, this _is_ a correct test. :+1:

File: features/running-tests.feature (hunk 2 above)
Comment (bittner) [reply features/running-tests.feature]: Hmmm, not sure if this `Then` should just test that `django_ready` is called, or that Django is actually _ready_. :thinking:

File: docs/usage.rst [hunk 4]
```diff
@@ -36,9 +36,10 @@ Examples:
 Django’s testing client
 -----------------------
 
-Attached to the context is an instance of TestCase.  You can access it
-via ``context.test``.  This means you can do things like use Django’s
-testing client.
+Internally, Django's TestCase or LiveServerTestCase is used to maintain database
+transactions and the live test server.
```
[the remark this answers is not in the document]
Comment (bittner) [reply docs/usage.rst]: Sure. But maybe it's more a "test live server" (i.e. a live server / runserser in the test run) rather than a "live test server" (a test server / a host for manual testing that behaves like a production aka "live" instance).

I know this discussion sounds ridiculous, but I'm sure it's not. The more self-explanatory it is, the less room for confusion there is, the better.

**Comment by mixxorz** [comment]
* Update wording on docs

How's that?

**Comment by bittner** [comment]
Well, I hate to say it, but ... (argh! I really just wanted to say "You're awesome!" when I saw your commit notification!) :disappointed: 

Mentioning the `LiveServerTestCase` was nice. But it's okay like that. Less is more!

File: docs/usage.rst [hunk 5]
```diff
@@ -90,19 +88,36 @@ regular TestCases.  So you can do something like:
 
 And you don’t have to clean the database yourself.
 
-If you have `factories`_ you want to instantiate on a per-scenario basis,
-you can initialize them in ``environment.py`` like this:
+django_ready hook
+-----------------
+
+You can add a ``django_ready`` method in your ``environment.py`` file in case
```
Comment (bittner) [inline docs/usage.rst]: Ah, it's actually a _function_, not a method. But nevermind. No need to be that picky.

**Comment by mixxorz** [comment]
Sorry 😅

The reason why I wrote this line was to tell people that when writing tests with behave-django, write it as if it's running inside a regular Django TestCase. I accidentally made it more verbose than it should have been.

**Comment by bittner** [comment]
@mixxorz I think you can merge the changes.
