### ISSUE TITLE
Unable to access context.test in before_scenario

### ISSUE THREAD

**Issue by craiga** [behave/behave-django#46]
We've set up `before_scenario` to swap out Django's test client with Django Rest Framework's `APIClient`:

```
from rest_framework.test import APIClient

def before_scenario(context, scenario):
    context.test.client = APIClient()
```

This worked in 0.5.0. In 1.0.0, it seems that I can't access `context.test` at this point:

```
Exception AttributeError: 'PatchedContext' object has no attribute 'test'
Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    main()
  File "manage.py", line 26, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/behave_django/management/commands/behave.py", line 128, in handle
    exit_status = behave_main(args=behave_args)
  File "/usr/local/lib/python3.6/site-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 693, in run_with_paths
    return self.run_model()
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 471, in run_model
    self.run_hook('before_all', context)
  File "/usr/local/lib/python3.6/site-packages/behave_django/environment.py", line 91, in run_hook
    behave_run_hook(self, name, context, *args)
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 405, in run_hook
    self.hooks[name](context, *args)
  File "features/environment.py", line 14, in before_all
    context.test.client = APIClient()
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 214, in __getattr__
    raise AttributeError(msg)
AttributeError: 'PatchedContext' object has no attribute 'test'
```

As far as I can tell, I should be able to access `context.test` here.

**Comment by bittner** [comment]
Ouch, that hurts!  :worried: 

We should write tests that check all test clients people use, including `rest_framework.test.APIClient`.

**Comment by bittner** [comment]
The relevant changes: https://github.com/behave/behave-django/compare/0.5.0...1.0.0#diff-3fd86c37800e90054aa0f6b2b57a0822

**Comment by bittner** [comment]
@mixxorz This is probably related to the [changes we introduced](https://github.com/behave/behave-django/commit/230559cd6d679d7414710c802de6e850663626e7) for running the tests. Can you spot what breaks the @craiga's use case?

I'm wondering if we should encourage setting `context.test.client` as in the example above or provide an alternative solution. This possibility should then be mentioned in our docs.

**Comment by mixxorz** [comment]
Wow sorry I didn't notice this sooner.

Is there any particular reason you have to attach `APIClient` to `test` and not just directly on `context`?

e.g.

```python
context.client = APIClient()
```

And to ask the bigger question, are there any benefits in adding `test` to the context in `before_scenario`?

**Comment by Paschmid** [comment]
I'm not sure if it's the same problem but it looks quite similar and on 0.5.0 it worked as well. I got this when I tried to access the base_url of the context in the before_scenario function:

```
Exception AttributeError: 'PatchedContext' object has no attribute 'base_url'
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/behave_django/management/commands/behave.py", line 128, in handle
    exit_status = behave_main(args=behave_args)
  File "/usr/local/lib/python3.6/site-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 693, in run_with_paths
    return self.run_model()
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 483, in run_model
    failed = feature.run(self)
  File "/usr/local/lib/python3.6/site-packages/behave/model.py", line 523, in run
    failed = scenario.run(runner)
  File "/usr/local/lib/python3.6/site-packages/behave/model.py", line 867, in run
    runner.run_hook('before_scenario', runner.context, self)
  File "/usr/local/lib/python3.6/site-packages/behave_django/environment.py", line 91, in run_hook
    behave_run_hook(self, name, context, *args)
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 405, in run_hook
    self.hooks[name](context, *args)
  File "entry/features/environment.py", line 40, in before_scenario
    context.driver.get(context.base_url)
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 214, in __getattr__
    raise AttributeError(msg)
AttributeError: 'PatchedContext' object has no attribute 'base_url'

**Comment by craiga** [comment]
@mixxorz The thought was that `context.test.client` exists, so should be replaced. Having `context.test.client` and `context.client` is untidy.

Swapping `context.test.client` for `context.client` is a workaround though.

**Comment by mixxorz** [comment]
Hmm I see. Well I'm convinced. I'm taking a look.

**Comment by mixxorz** [comment]
Can you guys try out the [refactor-monkey-patch](https://github.com/behave/behave-django/tree/refactor-monkey-patch) branch and check if it works?

**Comment by Paschmid** [comment]
Now I get this error even without the -S flag:

```
Exception AssertionError: Web browser automation is not available. This scenario step can not be run with the --simple or -S flag.
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Datacenter\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\Datacenter\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Datacenter\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Datacenter\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Datacenter\AppData\Local\Programs\Python\Python35\lib\site-packages\behave_django\management\commands\behave.py", line 128, in handle
    exit_status = behave_main(args=behave_args)
  File "C:\Users\Datacenter\AppData\Local\Programs\Python\Python35\lib\site-packages\behave\__main__.py", line 109, in main
    failed = runner.run()
  File "C:\Users\Datacenter\AppData\Local\Programs\Python\Python35\lib\site-packages\behave\runner.py", line 672, in run
    return self.run_with_paths()
  File "C:\Users\Datacenter\AppData\Local\Programs\Python\Python35\lib\site-packages\behave\runner.py", line 693, in run_with_paths
    return self.run_model()
  File "C:\Users\Datacenter\AppData\Local\Programs\Python\Python35\lib\site-packages\behave\runner.py", line 483, in run_model
    failed = feature.run(self)
  File "C:\Users\Datacenter\AppData\Local\Programs\Python\Python35\lib\site-packages\behave\model.py", line 523, in run
    failed = scenario.run(runner)
  File "C:\Users\Datacenter\AppData\Local\Programs\Python\Python35\lib\site-packages\behave\model.py", line 867, in run
    runner.run_hook('before_scenario', runner.context, self)
  File "C:\Users\Datacenter\AppData\Local\Programs\Python\Python35\lib\site-packages\behave_django\environment.py", line 104, in run_hook
    behave_run_hook(self, name, context, *args)
  File "C:\Users\Datacenter\AppData\Local\Programs\Python\Python35\lib\site-packages\behave\runner.py", line 405, in run_hook
    self.hooks[name](context, *args)
  File "entry\features\environment.py", line 40, in before_scenario
    context.driver.get(context.base_url)
  File "C:\Users\Datacenter\AppData\Local\Programs\Python\Python35\lib\site-packages\behave_django\environment.py", line 11, in base_url
    'Web browser automation is not available.'
AssertionError: Web browser automation is not available. This scenario step can not be run with the --simple or -S flag.
```
The test is now accessible but there is no live_server_url which causes the error.

**Comment by craiga** [comment]
@mixxorz I'm now able to access `client.test` in `before_scenario`, but it looks like changes being made to that object don't make it through to my step definitions.

      Traceback (most recent call last):
        File "/usr/local/lib/python3.6/site-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.6/site-packages/behave/model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "features/steps/authentication_steps.py", line 30, in login_as_member
          context.test.client.force_authenticate(user=context.member.user)
      AttributeError: 'Client' object has no attribute 'force_authenticate'

(note that `force_authenticate` is a method provided by DRF's test client)

[Looking at the branch you've created](https://github.com/behave/behave-django/compare/refactor-monkey-patch), I wonder if `django_test_runner.setup_test` needs to be called before `behave_run_hook`?

**Comment by mixxorz** [comment]
For your first issue, that is expected. `-S` makes behave-django use a regular `TestCase` which doesn't use a live server, but the regular Django test `Client` will still work there.

As for the main issue, the problem is that `behave_run_hook` needs to run before the test is initialized so that the `TestCase` can pick up the fixtures set in `before_scenario`. I'll work on it a bit more.

**Comment by mixxorz** [comment]
Okay so here's how it works right now:

1. Create instance of Django TestCase and add it to `context.test`
2. Run `behave_run_hook` which will run your `before_scenario` function
3. Setup the test case with `test._pre_setup()` and etc.

Your `before_scenario` function needs to run before `_pre_setup()` because `before_scenario` is where you initialize fixtures, and `_pre_setup()` is where Django loads them to the test database.

Unfortunately, `_pre_setup()` is also where Django initializes its test client. So anything you assign to `test.client` will get overwritten.

Sorry guys, I don't think there's a way to fix this without breaking fixtures. That said, this will only happen if you use specifically use `test.client`. You could still use a different name. Maybe `test.api` or `test.api_client`.

**Comment by Paschmid** [comment]
I think you misunderstood my problem. I ran "python manage.py behave" WITHOUT specifying the -S flag but it still complained that Web browser automation is not available. The problem is that the live_server_url is not properly initialized. The only thing I do in before_scenario is calling context.base_url and not setting another test client...

**Comment by mixxorz** [comment]
You're right, I did misunderstand. Haha my bad. Lemme check that out.

**Comment by mixxorz** [comment]
Okay. So totally new approach. I've added a new hook called `before_django` that you can declare in your `environment.py`. This runs after the Django test case has been set up. That means the live server is running at this point and the database is in a transaction. If you need to access things that require the testcase to be set up like `base_url`, `get_url()`, overriding members on `test`, you can do it here.

Does this work for you guys?

**Comment by Paschmid** [comment]
I tested it and it worked for me :)

**Comment by bittner** [comment]
Maybe `before_django` is not the best name for a hook that we explain as _"runs after the Django test case [has been set up]"_. I understand the motivation for the name, but the wording is a bit confusing. What do you guys think? How about `django_ready`, or some other name that conveys the purpose more clearly?

**Comment by craiga** [comment]
I’m about to go on holiday and I’m trying to spend that time away from code, so it’s going to take me a little while to look at this. Apologies in advance.

**Comment by mixxorz** [comment]
@bittner yeah definitely. The name is just something I came up with at the time, not necessarily final. I like `django_ready` better.

**Comment by bittner** [comment]
@craiga Back from your holidays? If you could confirm that the new approach is working we may consider packing the changes into a new release.

**Comment by craiga** [comment]
I am (for a short time at least 😎). Thanks for the nudge.

I checked out `refactor_monkey_patch` and rolled back the workaround to this issue, but continue to get the same error.

```
Exception AttributeError: 'PatchedContext' object has no attribute 'test'
Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    main()
  File "manage.py", line 26, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/behave_django/management/commands/behave.py", line 128, in handle
    exit_status = behave_main(args=behave_args)
  File "/usr/local/lib/python3.6/site-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 693, in run_with_paths
    return self.run_model()
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 483, in run_model
    failed = feature.run(self)
  File "/usr/local/lib/python3.6/site-packages/behave/model.py", line 523, in run
    failed = scenario.run(runner)
  File "/usr/local/lib/python3.6/site-packages/behave/model.py", line 867, in run
    runner.run_hook('before_scenario', runner.context, self)
  File "/usr/local/lib/python3.6/site-packages/behave_django/environment.py", line 101, in run_hook
    behave_run_hook(self, name, context, *args)
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 405, in run_hook
    self.hooks[name](context, *args)
  File "features/environment.py", line 21, in before_scenario
    context.test.client = APIClient()
  File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 214, in __getattr__
    raise AttributeError(msg)
AttributeError: 'PatchedContext' object has no attribute 'test'
```

**Comment by craiga** [comment]
If this fixes @Paschmid's issue it should probably be included in the new release, but the original issue hasn't been fixed.

**Comment by mixxorz** [comment]
`test` really isn't accessible in `before_scenario`, but a workaround is to use a new hook called `before_django` and write the modifications to the test instance there. Is this not a workable solution in your case?

**Comment by bittner** [comment]
@craiga Can you confirm that when using `before_django` it fixes your issue?

@mixxorz Should we then rename `before_django` to `django_ready` or something similar before issuing a new release?

**Comment by mixxorz** [comment]
@bittner definitely.
